// Everything the scaffolder knows about the framework, generated from the framework itself: the dependency
// versions a generated app pins, and the deploy targets with the command each is shipped by. Both would rot
// silently if typed out here — add a target to `deploy/presets.ts` and the CLI offers it after a rebuild.
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { pathToFileURL } from 'node:url';

const require = createRequire(import.meta.url);
const packageDir = join(import.meta.dirname, '..');

const frameworkManifest = require.resolve('@rshono/core/package.json');
const framework = JSON.parse(readFileSync(frameworkManifest, 'utf8'));
const frameworkDir = dirname(frameworkManifest);

const presetsPath = join(frameworkDir, 'dist', 'deploy', 'presets.js');
let presets;
try {
  presets = await import(pathToFileURL(presetsPath).href);
} catch (cause) {
  throw new Error(`[create-rshono] cannot read ${presetsPath} — build the framework first (\`pnpm --filter @rshono/core build\`).`, { cause });
}

/**
 * The versions the framework is *tested* against, not the ranges it merely accepts. `react` and `react-dom` are
 * exact in rshono's own devDependencies, and copying the declaration verbatim carries that into every app.
 */
const TEMPLATE_DEPS = ['hono', 'react', 'react-dom', 'typescript', '@types/node', '@types/react'];

const tested = {};
for (const name of TEMPLATE_DEPS) {
  const range = framework.devDependencies[name];
  if (!range) throw new Error(`[create-rshono] rshono no longer declares a tested version of "${name}" — update TEMPLATE_DEPS.`);
  tested[name] = range;
}

const nodeEngine = framework.engines?.node;
if (!nodeEngine) throw new Error('[create-rshono] rshono declares no engines.node — a scaffolded app has no floor to state.');

const targets = presets.DEPLOY_TARGETS.map((name) => {
  const hint = presets.deployHintFor(name);
  if (!hint) throw new Error(`[create-rshono] deploy target "${name}" has no deployHint.`);
  return { name, hint };
});

const entries = (record) =>
  Object.entries(record)
    .map(([key, value]) => `  ${/^[a-z][a-z\d]*$/i.test(key) ? key : `'${key}'`}: '${value}',`)
    .join('\n');

const file = `// GENERATED by scripts/codegen.mjs from packages/core — do not edit. Run \`pnpm --filter @rshono/create codegen\`.

/** The framework release a scaffolded app is pinned to: this package and rshono ship together. */
export const RSHONO_VERSION = '${framework.version}';

/**
 * The Node range rshono declares, restated in every scaffolded app's \`engines\` — so a CI image or a contributor
 * on an older Node hears it from their package manager rather than from a stack trace.
 */
export const NODE_ENGINE = '${nodeEngine}';

/**
 * The dependency versions rshono is tested against, copied from its own manifest. Exact where it is exact:
 * React's RSC internals are coupled across builds, and a generated app has no workspace overrides.
 */
export const FRAMEWORK_DEPS = {
${entries(tested)}
} as const;

/** Every \`deploy\` target the installed framework knows, with the command that ships what it built. */
export const DEPLOY_TARGETS = [
${targets.map((target) => `  { name: '${target.name}', hint: '${target.hint.replaceAll("'", "\\'")}' },`).join('\n')}
] as const;

export type DeployTargetName = (typeof DEPLOY_TARGETS)[number]['name'];
`;

const outDir = join(packageDir, 'src', 'generated');
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'framework.ts'), file);

console.log(`  • generated src/generated/framework.ts — rshono ${framework.version}, node ${nodeEngine}, ${targets.length} deploy target(s)`);
